deter_project_link: "http://deter-project.org/"
contact_link: "http://info.deterlab.net/contact_deterlab"

deter_lab:
  # wsdl: "https://users.isi.deterlab.net:52323/axis2/services/%s?wsdl"
  wsdl: "https://spidev.isi.deterlab.net:52323/axis2/services/%s?wsdl"
  #wsdl: "https://128.9.160.249:52323/axis2/services/%s?wsdl"
