# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b66242219185c7cda78e41432e0db1ea99d3a0615f1d59c84600892e9cee3ac816b8485a211b6d9466e962855302f3c094fdca56ff4dc88f6d56b3862dafb11

test:
  secret_key_base: ee65bc1132578e8ae356805cf1f1fa23beb9e8feda37047fa81116e297a7aef25272a8122a7dfe0ce8fb04be38be360bec0c038196cdfe5aa7ec11272acf630f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
