class LibraryMember < Struct.new(:uid, :permissions)

  ADD_EXPERIMENT        = "ADD_EXPERIMENT"
  REMOVE_EXPERIMENT     = "REMOVE_EXPERIMENT"
  READ_LIBRARY          = "READ_LIBRARY"
  MODIFY_LIBRARY_ACCESS = "MODIFY_LIBRARY_ACCESS"
  ALL_PERMS             = [ ADD_EXPERIMENT, REMOVE_EXPERIMENT, READ_LIBRARY, MODIFY_LIBRARY_ACCESS ]

end
